### Create Orders
POST http://localhost:3000/api/order
Content-Type: application/json

{
  "user": "68f4f5eff88f4f943b90108d",
  "orderItems": [
    {
      "product": "68f31677b2b33a81bebd7ffb",
      "quantity": 2,
      "priceAtOrder": 50000
    }
  ],
  "totalAmount": 100000
}

### Get all orders
GET http://localhost:3000/api/order

### Get Order by ID
GET http://localhost:3000/api/order/68f4ff6b301e8c5c5ba11122

### Update Order Status
PUT http://localhost:3000/api/order/68f4ff6b301e8c5c5ba11122
Content-Type: application/json

{
    "status":"Shipped"
}